version: '3'
name: request-logger

services:
    web:
        image: nginx
        container_name: nginx
        volumes:
            - ../src/nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        networks:
            - nginx.docker
    
    requestlogger:
        container_name: request-logger
        build:
            context: ../src
            dockerfile: RequestLogger\Dockerfile
        networks:
            - nginx.docker
        env_file:
            - .env
            
    mockserver:
        image: mockserver/mockserver:latest
        container_name: mock-server
        environment:
            MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
            MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
            MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
        volumes:
            - ../src/MockServerConfig/initializerJson.json:/config/initializerJson.json:ro
        networks:
            - nginx.docker
        
    postgres:
        image: postgres:12.15
        container_name: postgres
        hostname: postgres
        ports:
            - "5452:5432"
        volumes:
            - rl_postgres_data:/var/lib/postgresql/data
            - rl_postgres_data_backups:/backups
        env_file:
            - .env
        networks:
            - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker

volumes:
    rl_postgres_data: {}
    rl_postgres_data_backups: {}